name: pylandstats-dev

channels:
  - conda-forge

dependencies:
  - numpy
  - pandas
  - geopandas
  - matplotlib-base
  - rasterio
  - scipy>=1.0.0
  - transonic>=0.4.0

  # linting/testing
  - black
  - bump2version
  - coverage
  - coveralls
  - isort
  - flake8
  - flake8-docstrings  
  - m2r2
  - pydocstyle
  - pytest
  - pre-commit
  - sphinx
