name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment-dev.yml') }}

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true  # required for caching
          show-channel-urls: true
          channel-priority: strict
          activate-environment: pylandstats-dev
          environment-file: environment-dev.yml

      - name: Install pylandstats
        run: |
          pip install .[geo]
          conda list
          conda info --all

      - name: Lint code
        run: |
          isort pylandstats --check-only
          black . --check --diff
          flake8 .

      - name: Test docs
        run: make -C ./docs html

      - name: Test code
        run: |
          coverage run --source ./pylandstats --module pytest --verbose
          coverage xml -i
          coverage report -m

      - name: Test notebooks
        run: |
          git clone https://github.com/martibosch/pylandstats-notebooks
          cd pylandstats-notebooks
          make execute_notebooks
          cd ..          

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
